jobs:
  cdk-continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - run: npm install

      - run: |
          cd src/process
          npm install

      - run: npm run build

      - name: Bootstrap CDK Environment
        run: npx cdk bootstrap aws://455697799413/eu-north-1

      - name: Deploy CDK Stack
        run: npx cdk deploy --require-approval never --method=direct
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
          SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}
